version: '3.8'
services:
  keycloak-mysql:
  # keycloak-mysql is used to store keycloak realms data  
    container_name: forex-keycloak-mysql
    image: mysql:8
    volumes:
      - ./volume-data/mysql_keycloak_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
  keycloak:
  # keycloak is providing authorizing service 
    container_name: forex-keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--import-realm" ]
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8181:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - keycloak-mysql
  zipkin:
  # zipkin is used for distributed tracing  
    container_name: forex-zipkin
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - "9411:9411"
    depends_on:
      - keycloak  
  zookeeper:
  # zookeeper and kafka provide aync communication
    container_name: forex-zookeeper
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
  kafka:
  # zookeeper and  kafka provide aync communication  
    container_name: forex-kafka
    image: wurstmeister/kafka
    ports:
    - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  naming-server:
    container_name: forex-naming-server
    image: forex/naming-server:v1
    ports:
    - "8761:8761"
  api-gateway:
    container_name: forex-api-gateway
    image: forex/api-gateway:v1
    ports:
    - "8765:8765"
    links:
    - naming-server
  currency-exchange:
    container_name: forex-currency-exchange
    image: forex/currency-exchange:v1
    ports:
    - "8101:8101"
    links:
    - naming-server
    - kafka
  currency-conversion:
    container_name: forex-currency-conversion
    image: forex/currency-conversion:v1
    ports:
    - "8001:8001"
    links:
    - naming-server
    - kafka    
    