INSERT INTO EXCHANGE_VALUE(id,CURRENCY_FROM,CURRENCY_TO,rate,PORT)
values(10001,'USD','INR',65,0);

INSERT INTO EXCHANGE_VALUE(id,CURRENCY_FROM,CURRENCY_TO,rate,PORT)
values(10002,'EUR','INR',75,0);

INSERT INTO EXCHANGE_VALUE(id,CURRENCY_FROM,CURRENCY_TO,rate,PORT)
values(10003,'AUD','INR',25,0);